### ISSUE TITLE
Reduce execution time of `.DefaultDASimulations()`

### ISSUE THREAD

**Issue by Puzzled-Face** [openpharma/crmPack#821]
`.DefaultDASimulations()` has a relatively long execution time.  Can this be improved?

```
startTime <- Sys.time()
.DefaultDASimulations()
endTime <- Sys.time()

endTime - startTime
Time difference of 56.84297 secs
```

The same is true, to a lesser extent, of `DefaultSimulations()`.

```
startTime <- Sys.time()
.DefaultSimulations()
endTime <- Sys.time()

endTime - startTime
Time difference of 2.711638 secs
```

**Comment by Puzzled-Face** [comment]
Most likely due to the dose grid in `DefaultDADesign()`:

```
  emptydata <- DataDA(
    doseGrid = c(0.1, 0.5, 1, 1.5, 3, 6, seq(from = 10, to = 80, by = 2)),
    Tmax = 60
  )
```

**Comment by Puzzled-Face** [comment]
@danielinteractive I think a potential solution would be to mock `.DefaultDASimulations()` during tests so that rather than creating a new instance every time the default constructor is called, we simply load the data from disk.  Reading the `Rds` file should be effectively instant, so that close to a minute would be saved every time the default constructor is called.

To do this.

- Create a `testdata` folder under `tests/testthat`
- Run `.DefaultDASimulations()` ineractively and save the object to an Rds file in `testdata`
- Create `helper-mocks.R in `tests/testthat`
- In `helper-mocks.R` create the function below
- `source` `helper-mocks.R` at the start of every test file that calls `.DefaultDASimulations()`

The mocked function would be

```
local_mocked_bindings(
  .DefaultDASimulations = function(...){
    readRDS(testthat::test_path("testdata", "DefaultDASimulations.Rds")
  }
)
```
or similar.

The major advantage of this approach would be that there are no changes necessary to any package code and all test results would remain unchanged.

See [here](https://testthat.r-lib.org/reference/local_mocked_bindings.html) for more details on mocking tools.

**Comment by Puzzled-Face** [comment]
We could even modify `.DefaultDASimulations()` itself to load a static `.Rds` file as well.

This could be created by `usethis::use_data(internal = TRUE)`.  See section 7.2 of [this](https://r-pkgs.org/data.html#sec-data-extdata) for more information.

**Comment by danielinteractive** [comment]
Yeah good idea, I think this kind of caching makes sense
