### ISSUE TITLE
example.pdf vignette typo

### ISSUE THREAD

**Issue by wwojciech** [openpharma/crmPack#854]
https://github.com/openpharma/crmPack/blob/75659a9bd9c856ac5ae33ddaed52eb1cef79df59/vignettes/example.Rmd#L824

twice `or` in the following sentence: 
"..., or reached a pre-specified probability of the next dose being in the target toxicity interval (StoppingTargetProb) `or or` target biomarker interval...".

**Comment by wwojciech** [comment]
Hi @danielinteractive - just spotted this small typo and registered this issue if you do not mind.

**Comment by Puzzled-Face** [comment]
Good to see you again, @wwojciech.  I hope all is well.  I will fix this.
